keys:
  age:
    - &ssh      age1qqquny76zrfgy4thjv77fwntzfnlfds02d5lr5pguca4wpa9z5js0qpzal  # converted from ssh ed_25519 key
    - &general  age1fp53ld8q6a7uswh84pa8ys9yhvutvlqu35x3ex3pz6d7gw6l0v5q7qngtr
    - &akiko    age13elz7mxhqn7vpmskfltle4tg0skk6jxaa9dzlyc8efpmfcde79pq35el55
    - &jethro   age1k2u5ygvyxus5wd53yk3434q02m3r6l2jc7q36x8qae5tx55049eq0l5sd8
    - &phuong   age1w7twg5vdlmysah6aewz5yd3qxuqfpj9fcn3gwdp7zal6k2kxgcuqdyg7qn
  pgp:
    - &gpg      115AB673F93A781A1501E71B7F6354E5A6AAADDF

# all secrets can be open with gpg and ssh key
# general secret can be open by any individual key
# individual secret can be open by individual key
creation_rules:
  - path_regex: secrets/general.yaml$
    key_groups:
      - age:
        # per-device keys
        - *akiko
        - *jethro
        - *phuong

        # cover-all keys
        - *ssh
        - *general
        pgp: [ *gpg ]

  - path_regex: secrets/desktop.yaml$
    key_groups:
      - age:
        - *akiko
        - *ssh
        pgp: [ *gpg ]

  - path_regex: secrets/akiko.yaml$
    key_groups:
      - age:
        - *akiko
        - *ssh
        pgp: [ *gpg ]

  - path_regex: secrets/jethro.yaml$
    key_groups:
      - age:
        - *jethro
        - *ssh
        pgp: [ *gpg ]

  - path_regex: secrets/phuong.yaml$
    key_groups:
      - age:
        - *phuong
        - *ssh
        pgp: [ *gpg ]

