return function(vim, lsp_autostart)
  require('LuaMyNvim.parts.filetype')(vim)
  require('LuaMyNvim.parts.keymap')(vim)
  require('LuaMyNvim.parts.opt')(vim)

  require('LuaMyNvim.plugins.barbar')(vim)
  require('LuaMyNvim.plugins.cmp')(vim)
  require('LuaMyNvim.plugins.gitsigns')(vim)
  require('LuaMyNvim.plugins.lspconfig')(vim, lsp_autostart)
  require('LuaMyNvim.plugins.lualine')(vim)
  require('LuaMyNvim.plugins.luasnip')(vim)
  require('LuaMyNvim.plugins.neo-tree')(vim)
  require('LuaMyNvim.plugins.notify')(vim)
  require('LuaMyNvim.plugins.colorscheme')(vim)
  require('LuaMyNvim.plugins.spectre')(vim)
  require('LuaMyNvim.plugins.telescope')(vim)
  require('LuaMyNvim.plugins.toggleterm')(vim)
  require('LuaMyNvim.plugins.treesitter')(vim)
  require('LuaMyNvim.plugins.trouble')(vim)
  require('LuaMyNvim.plugins.vimtex')(vim)

  require('LuaMyNvim.plugins.misc')(vim)
end
