admin_id = 629325599

endpoints = [
  { name = "ohmygpt", url = "https://api.ohmygpt.com/v1" },
  { name = "novita", url = "https://api.novita.ai/v3/openai"},
]
default_endpoint = "ohmygpt"

models = [
  # openai
  { prefix = "o3 ", name = "o3" },
  { prefix = "51 ", name = "gpt-5.1" },
  { prefix = "52 ", name = "gpt-5.2" },

  # deepseek
  { prefix = "d ", name = "deepseek-chat" },
  { prefix = "r ", name = "deepseek-reasoner" },
  { prefix = "dn ", name = "deepseek/deepseek-r1", endpoint = "novita" },

  # google
  { prefix = "gf ", name = "gemini-3-flash-preview" },
  { prefix = "gp ", name = "gemini-3-pro-preview" },

  # claude
  { prefix = "ch ", name = "claude-haiku-4-5" },
  { prefix = "co ", name = "claude-opus-4-5" },
  { prefix = "cs ", name = "claude-sonnet-4-5" },

  # custom
  { prefix = "tp ", name = "gemini-3-pro-preview-legacy-support", system_prompt = "The user will send you some text and optionally a language name. You need to translate it into Chinese. If the user sends a single word, you should also include some expanations and usages. Note that your answer should also in Chinese." },
  { prefix = "t ", name = "gemini-3-flash-preview-legacy-support", system_prompt = "The user will send you some text and optionally a language name. You need to translate it into Chinese. If the user sends a single word, you should also include some expanations and usages. Note that your answer should also in Chinese." },
]

