# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  aribb24 = {
    pname = "aribb24";
    version = "v1.0.3";
    src = fetchFromGitHub {
      owner = "nkoriyama";
      repo = "aribb24";
      rev = "v1.0.3";
      fetchSubmodules = false;
      sha256 = "sha256-5/ThUL+13gAgSm2kCthcd5MvqT6pbDR3kGNWj21ObaQ=";
    };
  };
  bullet = {
    pname = "bullet";
    version = "2.2.0";
    src = fetchurl {
      url = "https://pypi.org/packages/source/b/bullet/bullet-2.2.0.tar.gz";
      sha256 = "sha256-36D6gYEK0anmiIFcoE8kr4f/XNvoA7QvpjSx9Q/J2Ic=";
    };
  };
  eac-logchecker = {
    pname = "eac-logchecker";
    version = "0.8.1";
    src = fetchurl {
      url = "https://pypi.org/packages/source/e/eac_logchecker/eac_logchecker-0.8.1.tar.gz";
      sha256 = "sha256-aB2D7I7ntYGjlOGQv1D5GSmsNKEq8FhGCbtx+kJ+oXc=";
    };
  };
  efb-search_msg-middleware = {
    pname = "efb-search_msg-middleware";
    version = "0.1.0";
    src = fetchurl {
      url = "https://pypi.org/packages/source/e/efb-search_msg-middleware/efb-search_msg-middleware-0.1.0.tar.gz";
      sha256 = "sha256-FpqXaXA3e1eiF37gg6ojfR0LaK59eBdVcNU4Pc0YhYg=";
    };
  };
  efb-telegram-master = {
    pname = "efb-telegram-master";
    version = "2.3.1";
    src = fetchurl {
      url = "https://pypi.org/packages/source/e/efb-telegram-master/efb-telegram-master-2.3.1.tar.gz";
      sha256 = "sha256-s89M+QqUXf5TBPDrlJsaGCX2/SlvYp+U4gGyRUqojOk=";
    };
  };
  efb-wechat-slave = {
    pname = "efb-wechat-slave";
    version = "2.0.7";
    src = fetchurl {
      url = "https://pypi.org/packages/source/e/efb-wechat-slave/efb-wechat-slave-2.0.7.tar.gz";
      sha256 = "sha256-EFHR5Md22mlNeuiJBfSq12In4EgOzQpgjgt60zVAChw=";
    };
  };
  ehforwarderbot = {
    pname = "ehforwarderbot";
    version = "2.1.1";
    src = fetchurl {
      url = "https://pypi.org/packages/source/e/ehforwarderbot/ehforwarderbot-2.1.1.tar.gz";
      sha256 = "sha256-QUw95OmtFR0604032J8LYmpfp/sE2dMP8VK1Iw00CZs=";
    };
  };
  elf-info = {
    pname = "elf-info";
    version = "v0.3.0";
    src = fetchFromGitHub {
      owner = "kevin-lesenechal";
      repo = "elf-info";
      rev = "v0.3.0";
      fetchSubmodules = false;
      sha256 = "sha256-wbFVuoarOoxV9FqmuHJ9eZlG4rRqy1rsnuqbGorC2Rk=";
    };
  };
  filetype-nvim = {
    pname = "filetype-nvim";
    version = "15891eb2b138d54b08aef793c43901910ec6879f";
    src = fetchFromGitHub {
      owner = "nathom";
      repo = "filetype.nvim";
      rev = "15891eb2b138d54b08aef793c43901910ec6879f";
      fetchSubmodules = false;
      sha256 = "sha256-Fw7q2k8kGszmzHlSNUYWq4I1IUkmims0JUMMNDGcvSg=";
    };
    date = "2024-05-06";
  };
  geoip-cn = {
    pname = "geoip-cn";
    version = "5eff6e1e186f75c441f0a989d5f3987e71824cfc";
    src = fetchurl {
      url = "https://raw.githubusercontent.com/SagerNet/sing-geoip/5eff6e1e186f75c441f0a989d5f3987e71824cfc/geoip-cn.srs";
      sha256 = "sha256-a7BSmF5S1bMvefqt0j1+/CEg07YGKZYM5dmPnxNym+o=";
    };
    date = "2025-01-12";
  };
  geosite-cn = {
    pname = "geosite-cn";
    version = "1ca538b1f1efcbd3d53e013bf4cf0805061147de";
    src = fetchurl {
      url = "https://raw.githubusercontent.com/SagerNet/sing-geosite/1ca538b1f1efcbd3d53e013bf4cf0805061147de/geosite-cn.srs";
      sha256 = "sha256-X7ByMD+RuafhImu/X7vSk+4xl7eUrPLFZVHEQ2s6ZXo=";
    };
    date = "2025-02-08";
  };
  goauthing = {
    pname = "goauthing";
    version = "v2.3.4";
    src = fetchFromGitHub {
      owner = "z4yx";
      repo = "GoAuthing";
      rev = "v2.3.4";
      fetchSubmodules = false;
      sha256 = "sha256-BUvbUvkowbzS+m8CFtG1oimD/DmYUKTrLGfP2a2JA3U=";
    };
  };
  i3-volume = {
    pname = "i3-volume";
    version = "v3.9.0";
    src = fetchFromGitHub {
      owner = "hastinbe";
      repo = "i3-volume";
      rev = "v3.9.0";
      fetchSubmodules = false;
      sha256 = "sha256-vmyfEXJ/5TRWIJQCblYcy8owI03F+ARNAEd0ni5ublM=";
    };
  };
  libaribcaption = {
    pname = "libaribcaption";
    version = "v1.1.1";
    src = fetchFromGitHub {
      owner = "xqq";
      repo = "libaribcaption";
      rev = "v1.1.1";
      fetchSubmodules = false;
      sha256 = "sha256-x6l0ZrTktSsqfDLVRXpQtUOruhfc8RF3yT991UVZiKA=";
    };
  };
  logchecker = {
    pname = "logchecker";
    version = "0.14.0";
    src = fetchFromGitHub {
      owner = "OPSnet";
      repo = "Logchecker";
      rev = "0.14.0";
      fetchSubmodules = false;
      sha256 = "sha256-LirtDmR1/eVonXjyhbGluRiOPqo+I8tH8rjmFKYhbVM=";
    };
  };
  music-tag = {
    pname = "music-tag";
    version = "0.4.3";
    src = fetchurl {
      url = "https://pypi.org/packages/source/m/music-tag/music-tag-0.4.3.tar.gz";
      sha256 = "sha256-Cqtubu2o3w9TFuwtIZC9dFYbfgNWKrCRzo1Wh828//Y=";
    };
  };
  opentype-feature-freezer = {
    pname = "opentype-feature-freezer";
    version = "1.32.2";
    src = fetchurl {
      url = "https://pypi.org/packages/source/o/opentype-feature-freezer/opentype-feature-freezer-1.32.2.tar.gz";
      sha256 = "sha256-zckzIL/uTi8UVUdvK1YY2C9HwNhlMvG2lnNmatzCtXM=";
    };
  };
  pb = {
    pname = "pb";
    version = "2e26036844a58c38beff00733061bfe55fb176b8";
    src = fetchFromGitHub {
      owner = "SharzyL";
      repo = "pastebin-worker";
      rev = "2e26036844a58c38beff00733061bfe55fb176b8";
      fetchSubmodules = false;
      sha256 = "sha256-LsDssDJZqxtzPi1stAF0jd9u6QrnCvBkCOI3i8oO9a8=";
    };
    date = "2024-12-22";
  };
  pprp = {
    pname = "pprp";
    version = "0.2.7";
    src = fetchurl {
      url = "https://pypi.org/packages/source/p/pprp/pprp-0.2.7.tar.gz";
      sha256 = "sha256-2ednecxSsJONvH9XJ6GV3ExgdcPrUEAlYRpZt2Nrkw0=";
    };
  };
  python-ddns = {
    pname = "python-ddns";
    version = "3.0.2";
    src = fetchurl {
      url = "https://pypi.org/packages/source/d/ddns/ddns-3.0.2.tar.gz";
      sha256 = "sha256-2Q8iGc1gjv2gldMbLtoPOJUUH2He9fphB+lLrBHvgcQ=";
    };
  };
  rait = {
    pname = "rait";
    version = "278188c8bae13165aa70b6a2fbbb99101fd6f4cd";
    src = fetchgit {
      url = "https://gitlab.com/NickCao/RAIT";
      rev = "278188c8bae13165aa70b6a2fbbb99101fd6f4cd";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-6Y0s5/HUmWrZA6QmV5wYjB1M0Ab/jHM3TSruRpMRwtA=";
    };
    date = "2022-10-07";
  };
  rime-dict = {
    pname = "rime-dict";
    version = "f6583b1c4bf622a81ea77c03ef1d0decf31f01d9";
    src = fetchFromGitHub {
      owner = "xiaoTaoist";
      repo = "rime-dict";
      rev = "f6583b1c4bf622a81ea77c03ef1d0decf31f01d9";
      fetchSubmodules = false;
      sha256 = "sha256-YreRy3HJiO5QEZPe2JAl6o/tq7qQKTqFQ6B2gaurXj8=";
    };
    date = "2018-03-06";
  };
  rime-double-pinyin = {
    pname = "rime-double-pinyin";
    version = "69bf85d4dfe8bac139c36abbd68d530b8b6622ea";
    src = fetchFromGitHub {
      owner = "rime";
      repo = "rime-double-pinyin";
      rev = "69bf85d4dfe8bac139c36abbd68d530b8b6622ea";
      fetchSubmodules = false;
      sha256 = "sha256-UyVzp0TMq7yq5pXQpy7xkPnc1+RF8oVdIXzvrYqLfCQ=";
    };
    date = "2019-01-20";
  };
  rime-essay = {
    pname = "rime-essay";
    version = "eaa02871c473f258d604b3f713a4a9da7572b74c";
    src = fetchFromGitHub {
      owner = "rime";
      repo = "rime-essay";
      rev = "eaa02871c473f258d604b3f713a4a9da7572b74c";
      fetchSubmodules = false;
      sha256 = "sha256-yphk5RZRA6HMyxE/skRz4fsUeQC216JMfKJdCunYhBg=";
    };
    date = "2025-02-03";
  };
  rime-ice = {
    pname = "rime-ice";
    version = "a07cdd0f60ba56ec7fc0329fff7bf4637d02a08f";
    src = fetchFromGitHub {
      owner = "iDvel";
      repo = "rime-ice";
      rev = "a07cdd0f60ba56ec7fc0329fff7bf4637d02a08f";
      fetchSubmodules = false;
      sha256 = "sha256-mB5hmn+2p58TdilDz9ozGyibBqLAIjwGuu558Ye30JY=";
    };
    date = "2025-02-05";
  };
  rime-luna-pinyin = {
    pname = "rime-luna-pinyin";
    version = "1b3a2e58cd45e556efafb39c672fe8cb7ada3461";
    src = fetchFromGitHub {
      owner = "rime";
      repo = "rime-luna-pinyin";
      rev = "1b3a2e58cd45e556efafb39c672fe8cb7ada3461";
      fetchSubmodules = false;
      sha256 = "sha256-C0fB0S/m5GTvR0JygosQGAX+NAeP0xDypsjyggEV3mo=";
    };
    date = "2025-01-31";
  };
  rime-prelude = {
    pname = "rime-prelude";
    version = "3803f09458072e03b9ed396692ce7e1d35c88c95";
    src = fetchFromGitHub {
      owner = "rime";
      repo = "rime-prelude";
      rev = "3803f09458072e03b9ed396692ce7e1d35c88c95";
      fetchSubmodules = false;
      sha256 = "sha256-qLxkijfB/btd2yhUMbxmoNx6fKxpKYHBZoE7YEUKIu4=";
    };
    date = "2024-05-19";
  };
  rssbot = {
    pname = "rssbot";
    version = "v2.0.0-alpha.13";
    src = fetchurl {
      url = "https://github.com/iovxw/rssbot/releases/download/v2.0.0-alpha.13/rssbot-en-x86_64-unknown-linux-musl";
      sha256 = "sha256-xhyEG+or695T7/zmT8yWh1ME7A2oXn1ZLTxGiSwG2NY=";
    };
  };
  s1-helper = {
    pname = "s1-helper";
    version = "d86dbf1058150b59c3cb71f306a9812fab715c91";
    src = fetchFromGitHub {
      owner = "Fungx";
      repo = "Stage1stHelper";
      rev = "d86dbf1058150b59c3cb71f306a9812fab715c91";
      fetchSubmodules = false;
      sha256 = "sha256-EAtv7dY3Gr/lDJvfqfJXeztreErqhG/2+ZzBPKhAQFY=";
    };
    date = "2021-10-15";
  };
  spiceForMinted = {
    pname = "spiceForMinted";
    version = "9626453f7a5955f81ee892a53481704fc55f5b18";
    src = fetchFromGitHub {
      owner = "salatielGarcia";
      repo = "spiceForMinted";
      rev = "9626453f7a5955f81ee892a53481704fc55f5b18";
      fetchSubmodules = false;
      sha256 = "sha256-grgj4IRUY1pEsTjfvzqQHBhpBIMJh/YUC3am6MiujQ4=";
    };
    date = "2020-05-22";
  };
  subconverter = {
    pname = "subconverter";
    version = "v0.9.0";
    src = fetchurl {
      url = "https://github.com/tindy2013/subconverter/releases/download/v0.9.0/subconverter_linux64.tar.gz";
      sha256 = "sha256-iEptEWgmfroHb83VFxIVus+YwXlIq1JuTLvcrV96Ahc=";
    };
  };
  tree-sitter-just = {
    pname = "tree-sitter-just";
    version = "bb0c898a80644de438e6efe5d88d30bf092935cd";
    src = fetchFromGitHub {
      owner = "IndianBoy42";
      repo = "tree-sitter-just";
      rev = "bb0c898a80644de438e6efe5d88d30bf092935cd";
      fetchSubmodules = false;
      sha256 = "sha256-FwEuH/2R745jsuFaVGNeUTv65xW+MPjbcakRNcAWfZU=";
    };
    date = "2025-01-05";
  };
  vim-barbaric = {
    pname = "vim-barbaric";
    version = "bb4bef87417fc3ad92319f556f02d6658b401288";
    src = fetchFromGitHub {
      owner = "rlue";
      repo = "vim-barbaric";
      rev = "bb4bef87417fc3ad92319f556f02d6658b401288";
      fetchSubmodules = false;
      sha256 = "sha256-d1sH4FTxuXxC9/9ZHcX/xOvWkGmW3DN0DSXK+POdi/Q=";
    };
    date = "2021-05-19";
  };
  wemeet = {
    pname = "wemeet";
    version = "3.19.0.401";
    src = fetchurl {
      url = "https://updatecdn.meeting.qq.com/cos/bb4001c715553579a8b3e496233331d4/TencentMeeting_0300000000_3.19.0.401_x86_64_default.publish.deb";
      sha256 = "sha256-VN/rNn2zA21l6BSzLpQ5Bl9XB2hrMFIa0o0cy2vdLx8=";
    };
  };
}
