# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit
, fetchurl
, fetchFromGitHub
, dockerTools
,
}:
{
  aribb24 = {
    pname = "aribb24";
    version = "v1.0.3";
    src = fetchFromGitHub {
      owner = "nkoriyama";
      repo = "aribb24";
      rev = "v1.0.3";
      fetchSubmodules = false;
      sha256 = "sha256-5/ThUL+13gAgSm2kCthcd5MvqT6pbDR3kGNWj21ObaQ=";
    };
  };
  bullet = {
    pname = "bullet";
    version = "2.2.0";
    src = fetchurl {
      url = "https://pypi.org/packages/source/b/bullet/bullet-2.2.0.tar.gz";
      sha256 = "sha256-36D6gYEK0anmiIFcoE8kr4f/XNvoA7QvpjSx9Q/J2Ic=";
    };
  };
  eac-logchecker = {
    pname = "eac-logchecker";
    version = "0.8.1";
    src = fetchurl {
      url = "https://pypi.org/packages/source/e/eac_logchecker/eac_logchecker-0.8.1.tar.gz";
      sha256 = "sha256-aB2D7I7ntYGjlOGQv1D5GSmsNKEq8FhGCbtx+kJ+oXc=";
    };
  };
  efb-search_msg-middleware = {
    pname = "efb-search_msg-middleware";
    version = "0.1.0";
    src = fetchurl {
      url = "https://pypi.org/packages/source/e/efb-search_msg-middleware/efb-search_msg-middleware-0.1.0.tar.gz";
      sha256 = "sha256-FpqXaXA3e1eiF37gg6ojfR0LaK59eBdVcNU4Pc0YhYg=";
    };
  };
  efb-telegram-master = {
    pname = "efb-telegram-master";
    version = "2.3.1";
    src = fetchurl {
      url = "https://pypi.org/packages/source/e/efb-telegram-master/efb-telegram-master-2.3.1.tar.gz";
      sha256 = "sha256-s89M+QqUXf5TBPDrlJsaGCX2/SlvYp+U4gGyRUqojOk=";
    };
  };
  efb-wechat-slave = {
    pname = "efb-wechat-slave";
    version = "2.0.7";
    src = fetchurl {
      url = "https://pypi.org/packages/source/e/efb-wechat-slave/efb-wechat-slave-2.0.7.tar.gz";
      sha256 = "sha256-EFHR5Md22mlNeuiJBfSq12In4EgOzQpgjgt60zVAChw=";
    };
  };
  ehforwarderbot = {
    pname = "ehforwarderbot";
    version = "2.1.1";
    src = fetchurl {
      url = "https://pypi.org/packages/source/e/ehforwarderbot/ehforwarderbot-2.1.1.tar.gz";
      sha256 = "sha256-QUw95OmtFR0604032J8LYmpfp/sE2dMP8VK1Iw00CZs=";
    };
  };
  elf-info = {
    pname = "elf-info";
    version = "v0.3.0";
    src = fetchFromGitHub {
      owner = "kevin-lesenechal";
      repo = "elf-info";
      rev = "v0.3.0";
      fetchSubmodules = false;
      sha256 = "sha256-wbFVuoarOoxV9FqmuHJ9eZlG4rRqy1rsnuqbGorC2Rk=";
    };
  };
  factlang-vim = {
    pname = "factlang-vim";
    version = "dcc43d1246ace013a0705759095ed056ed441cab";
    src = fetchFromGitHub {
      owner = "PLSysSec";
      repo = "factlang.vim";
      rev = "dcc43d1246ace013a0705759095ed056ed441cab";
      fetchSubmodules = false;
      sha256 = "sha256-bEcv7TuermxP5b2qk2wxxyt1xYU30Fk5+fAW1oEuiQI=";
    };
    date = "2018-08-26";
  };
  filetype-nvim = {
    pname = "filetype-nvim";
    version = "15891eb2b138d54b08aef793c43901910ec6879f";
    src = fetchFromGitHub {
      owner = "nathom";
      repo = "filetype.nvim";
      rev = "15891eb2b138d54b08aef793c43901910ec6879f";
      fetchSubmodules = false;
      sha256 = "sha256-Fw7q2k8kGszmzHlSNUYWq4I1IUkmims0JUMMNDGcvSg=";
    };
    date = "2024-05-06";
  };
  fish-colored-man = {
    pname = "fish-colored-man";
    version = "1ad8fff696d48c8bf173aa98f9dff39d7916de0e";
    src = fetchFromGitHub {
      owner = "decors";
      repo = "fish-colored-man";
      rev = "1ad8fff696d48c8bf173aa98f9dff39d7916de0e";
      fetchSubmodules = false;
      sha256 = "sha256-uoZ4eSFbZlsRfISIkJQp24qPUNqxeD0JbRb/gVdRYlA=";
    };
    date = "2021-07-16";
  };
  geoip-cn = {
    pname = "geoip-cn";
    version = "6611af30ec3490a97b2a22a6b3b6623365f640e0";
    src = fetchurl {
      url = "https://raw.githubusercontent.com/SagerNet/sing-geoip/6611af30ec3490a97b2a22a6b3b6623365f640e0/geoip-cn.srs";
      sha256 = "sha256-9ys2jgSy06d/zfsq7U5lhIoVyo2R9Lou3FODA0qxruo=";
    };
    date = "2026-03-12";
  };
  geosite-cn = {
    pname = "geosite-cn";
    version = "d7c65e70d426afdc0fc0c607e75d26874a45248d";
    src = fetchurl {
      url = "https://raw.githubusercontent.com/SagerNet/sing-geosite/d7c65e70d426afdc0fc0c607e75d26874a45248d/geosite-cn.srs";
      sha256 = "sha256-72gfoRxyLt9zNN2HQkjp917GgBp3V6/FYUd0tQKpxJY=";
    };
    date = "2026-03-14";
  };
  goauthing = {
    pname = "goauthing";
    version = "v2.3.5";
    src = fetchFromGitHub {
      owner = "z4yx";
      repo = "GoAuthing";
      rev = "v2.3.5";
      fetchSubmodules = false;
      sha256 = "sha256-pZD54SoumOoSOE+r2Llgw71h8wkJ15pqkPX/LRS2R2Y=";
    };
  };
  libaribcaption = {
    pname = "libaribcaption";
    version = "v1.1.1";
    src = fetchFromGitHub {
      owner = "xqq";
      repo = "libaribcaption";
      rev = "v1.1.1";
      fetchSubmodules = false;
      sha256 = "sha256-x6l0ZrTktSsqfDLVRXpQtUOruhfc8RF3yT991UVZiKA=";
    };
  };
  logchecker = {
    pname = "logchecker";
    version = "0.14.2";
    src = fetchFromGitHub {
      owner = "OPSnet";
      repo = "Logchecker";
      rev = "0.14.2";
      fetchSubmodules = false;
      sha256 = "sha256-uli4H4FXHZ6x0ei/9k+X1oTQ7BsPkn591eLVcoNC0Kc=";
    };
  };
  music-tag = {
    pname = "music-tag";
    version = "0.4.3";
    src = fetchurl {
      url = "https://pypi.org/packages/source/m/music-tag/music-tag-0.4.3.tar.gz";
      sha256 = "sha256-Cqtubu2o3w9TFuwtIZC9dFYbfgNWKrCRzo1Wh828//Y=";
    };
  };
  opentype-feature-freezer = {
    pname = "opentype-feature-freezer";
    version = "1.32.2";
    src = fetchurl {
      url = "https://pypi.org/packages/source/o/opentype-feature-freezer/opentype-feature-freezer-1.32.2.tar.gz";
      sha256 = "sha256-zckzIL/uTi8UVUdvK1YY2C9HwNhlMvG2lnNmatzCtXM=";
    };
  };
  pb = {
    pname = "pb";
    version = "e7a49eb242afdb02f6218ca4ac4baad64600c7f0";
    src = fetchFromGitHub {
      owner = "SharzyL";
      repo = "pastebin-worker";
      rev = "e7a49eb242afdb02f6218ca4ac4baad64600c7f0";
      fetchSubmodules = false;
      sha256 = "sha256-qnJ1WYGB6eZCRRsilCSuIfPWyPYX8W7Me4N6hwpEt2c=";
    };
    date = "2026-03-13";
  };
  pprp = {
    pname = "pprp";
    version = "0.2.7";
    src = fetchurl {
      url = "https://pypi.org/packages/source/p/pprp/pprp-0.2.7.tar.gz";
      sha256 = "sha256-2ednecxSsJONvH9XJ6GV3ExgdcPrUEAlYRpZt2Nrkw0=";
    };
  };
  python-ddns = {
    pname = "python-ddns";
    version = "4.1.3";
    src = fetchurl {
      url = "https://pypi.org/packages/source/d/ddns/ddns-4.1.3.tar.gz";
      sha256 = "sha256-jf+sIID5HvR8u7M91gBTC1YW1nnYZII5vPdYsyucOTg=";
    };
  };
  rime-dict = {
    pname = "rime-dict";
    version = "f6583b1c4bf622a81ea77c03ef1d0decf31f01d9";
    src = fetchFromGitHub {
      owner = "xiaoTaoist";
      repo = "rime-dict";
      rev = "f6583b1c4bf622a81ea77c03ef1d0decf31f01d9";
      fetchSubmodules = false;
      sha256 = "sha256-YreRy3HJiO5QEZPe2JAl6o/tq7qQKTqFQ6B2gaurXj8=";
    };
    date = "2018-03-06";
  };
  rime-double-pinyin = {
    pname = "rime-double-pinyin";
    version = "01a13287cbd27819be1c34fa1ddc1b3643d5001b";
    src = fetchFromGitHub {
      owner = "rime";
      repo = "rime-double-pinyin";
      rev = "01a13287cbd27819be1c34fa1ddc1b3643d5001b";
      fetchSubmodules = false;
      sha256 = "sha256-iHaGHKwmhyciU6zKJRLyRETRR15QSHZ7ML1l4iAV6eM=";
    };
    date = "2025-09-24";
  };
  rime-essay = {
    pname = "rime-essay";
    version = "816b9eeab0f012e896d6c8d4f9b19f1524574378";
    src = fetchFromGitHub {
      owner = "rime";
      repo = "rime-essay";
      rev = "816b9eeab0f012e896d6c8d4f9b19f1524574378";
      fetchSubmodules = false;
      sha256 = "sha256-STrP4yU9zTHJnWXa93YTStLZVqBP8cBWggwRcoeTryA=";
    };
    date = "2026-01-06";
  };
  rime-ice = {
    pname = "rime-ice";
    version = "4fe519c81eb0f7add2707ea80af5efe73f9d55f5";
    src = fetchFromGitHub {
      owner = "iDvel";
      repo = "rime-ice";
      rev = "4fe519c81eb0f7add2707ea80af5efe73f9d55f5";
      fetchSubmodules = false;
      sha256 = "sha256-n1XFLBNxrbYf9c/6LzGV92zNQNXyJyCjpGtWR81YG5M=";
    };
    date = "2026-03-11";
  };
  rime-luna-pinyin = {
    pname = "rime-luna-pinyin";
    version = "d7b4e52f8021bbad5c5a99b2314ca1771cd6f222";
    src = fetchFromGitHub {
      owner = "rime";
      repo = "rime-luna-pinyin";
      rev = "d7b4e52f8021bbad5c5a99b2314ca1771cd6f222";
      fetchSubmodules = false;
      sha256 = "sha256-KSBwvr0xaC+3/TtIRwWY8j0Oan1sZYeJIek9xr24458=";
    };
    date = "2026-01-06";
  };
  rime-prelude = {
    pname = "rime-prelude";
    version = "db691d2420b8e656a79692a94f9db0fb3e7aa12b";
    src = fetchFromGitHub {
      owner = "rime";
      repo = "rime-prelude";
      rev = "db691d2420b8e656a79692a94f9db0fb3e7aa12b";
      fetchSubmodules = false;
      sha256 = "sha256-sllcT3Kq572xJvlh+j4zN0AUblFzXlhZtL9RGT/GY7g=";
    };
    date = "2025-12-30";
  };
  rssbot = {
    pname = "rssbot";
    version = "v2.0.0-alpha.13";
    src = fetchurl {
      url = "https://github.com/iovxw/rssbot/releases/download/v2.0.0-alpha.13/rssbot-en-x86_64-unknown-linux-musl";
      sha256 = "sha256-xhyEG+or695T7/zmT8yWh1ME7A2oXn1ZLTxGiSwG2NY=";
    };
  };
  s1-helper = {
    pname = "s1-helper";
    version = "d86dbf1058150b59c3cb71f306a9812fab715c91";
    src = fetchFromGitHub {
      owner = "Fungx";
      repo = "Stage1stHelper";
      rev = "d86dbf1058150b59c3cb71f306a9812fab715c91";
      fetchSubmodules = false;
      sha256 = "sha256-EAtv7dY3Gr/lDJvfqfJXeztreErqhG/2+ZzBPKhAQFY=";
    };
    date = "2021-10-15";
  };
  spiceForMinted = {
    pname = "spiceForMinted";
    version = "9626453f7a5955f81ee892a53481704fc55f5b18";
    src = fetchFromGitHub {
      owner = "salatielGarcia";
      repo = "spiceForMinted";
      rev = "9626453f7a5955f81ee892a53481704fc55f5b18";
      fetchSubmodules = false;
      sha256 = "sha256-grgj4IRUY1pEsTjfvzqQHBhpBIMJh/YUC3am6MiujQ4=";
    };
    date = "2020-05-22";
  };
  subconverter = {
    pname = "subconverter";
    version = "v0.9.0";
    src = fetchurl {
      url = "https://github.com/tindy2013/subconverter/releases/download/v0.9.0/subconverter_linux64.tar.gz";
      sha256 = "sha256-iEptEWgmfroHb83VFxIVus+YwXlIq1JuTLvcrV96Ahc=";
    };
  };
  tree-sitter-cpp = {
    pname = "tree-sitter-cpp";
    version = "8b5b49eb196bec7040441bee33b2c9a4838d6967";
    src = fetchFromGitHub {
      owner = "tree-sitter";
      repo = "tree-sitter-cpp";
      rev = "8b5b49eb196bec7040441bee33b2c9a4838d6967";
      fetchSubmodules = false;
      sha256 = "sha256-x3gDJ7/lukdOwfRFKrHZqV2zZ3Buqel5GcfbFnxStLU=";
    };
    date = "2026-02-24";
  };
  tree-sitter-just = {
    pname = "tree-sitter-just";
    version = "60df3d5b3fda2a22fdb3621226cafab50b763663";
    src = fetchFromGitHub {
      owner = "IndianBoy42";
      repo = "tree-sitter-just";
      rev = "60df3d5b3fda2a22fdb3621226cafab50b763663";
      fetchSubmodules = false;
      sha256 = "sha256-cul4U1V42l/nYcCvs2eVA09qSrPi34t0eJ/Pr/Ewfhc=";
    };
    date = "2026-02-09";
  };
  vim-barbaric = {
    pname = "vim-barbaric";
    version = "bad594b90aed9726ddd947782358321cce0cf610";
    src = fetchFromGitHub {
      owner = "rlue";
      repo = "vim-barbaric";
      rev = "bad594b90aed9726ddd947782358321cce0cf610";
      fetchSubmodules = false;
      sha256 = "sha256-u++AFNRHwwUd96dvF1PABEO3m20/YlrVeTuGVIyoFzE=";
    };
    date = "2026-01-29";
  };
  wemeet = {
    pname = "wemeet";
    version = "3.19.0.401";
    src = fetchurl {
      url = "https://updatecdn.meeting.qq.com/cos/bb4001c715553579a8b3e496233331d4/TencentMeeting_0300000000_3.19.0.401_x86_64_default.publish.deb";
      sha256 = "sha256-VN/rNn2zA21l6BSzLpQ5Bl9XB2hrMFIa0o0cy2vdLx8=";
    };
  };
  yazi-flavors = {
    pname = "yazi-flavors";
    version = "9511cb09cadcbf57e39a46b06a52d00957177175";
    src = fetchFromGitHub {
      owner = "yazi-rs";
      repo = "flavors";
      rev = "9511cb09cadcbf57e39a46b06a52d00957177175";
      fetchSubmodules = false;
      sha256 = "sha256-3RR8mi7CcVMDMitdTdaonFmfAIkeOzWK/CVKQmomIhE=";
    };
    date = "2026-03-13";
  };
}
