# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  aribb24 = {
    pname = "aribb24";
    version = "v1.0.3";
    src = fetchFromGitHub {
      owner = "nkoriyama";
      repo = "aribb24";
      rev = "v1.0.3";
      fetchSubmodules = false;
      sha256 = "sha256-5/ThUL+13gAgSm2kCthcd5MvqT6pbDR3kGNWj21ObaQ=";
    };
  };
  bullet = {
    pname = "bullet";
    version = "2.2.0";
    src = fetchurl {
      url = "https://pypi.org/packages/source/b/bullet/bullet-2.2.0.tar.gz";
      sha256 = "sha256-36D6gYEK0anmiIFcoE8kr4f/XNvoA7QvpjSx9Q/J2Ic=";
    };
  };
  eac-logchecker = {
    pname = "eac-logchecker";
    version = "0.8.1";
    src = fetchurl {
      url = "https://pypi.org/packages/source/e/eac_logchecker/eac_logchecker-0.8.1.tar.gz";
      sha256 = "sha256-aB2D7I7ntYGjlOGQv1D5GSmsNKEq8FhGCbtx+kJ+oXc=";
    };
  };
  efb-search_msg-middleware = {
    pname = "efb-search_msg-middleware";
    version = "0.1.0";
    src = fetchurl {
      url = "https://pypi.org/packages/source/e/efb-search_msg-middleware/efb-search_msg-middleware-0.1.0.tar.gz";
      sha256 = "sha256-FpqXaXA3e1eiF37gg6ojfR0LaK59eBdVcNU4Pc0YhYg=";
    };
  };
  efb-telegram-master = {
    pname = "efb-telegram-master";
    version = "2.3.1";
    src = fetchurl {
      url = "https://pypi.org/packages/source/e/efb-telegram-master/efb-telegram-master-2.3.1.tar.gz";
      sha256 = "sha256-s89M+QqUXf5TBPDrlJsaGCX2/SlvYp+U4gGyRUqojOk=";
    };
  };
  efb-wechat-slave = {
    pname = "efb-wechat-slave";
    version = "2.0.7";
    src = fetchurl {
      url = "https://pypi.org/packages/source/e/efb-wechat-slave/efb-wechat-slave-2.0.7.tar.gz";
      sha256 = "sha256-EFHR5Md22mlNeuiJBfSq12In4EgOzQpgjgt60zVAChw=";
    };
  };
  ehforwarderbot = {
    pname = "ehforwarderbot";
    version = "2.1.1";
    src = fetchurl {
      url = "https://pypi.org/packages/source/e/ehforwarderbot/ehforwarderbot-2.1.1.tar.gz";
      sha256 = "sha256-QUw95OmtFR0604032J8LYmpfp/sE2dMP8VK1Iw00CZs=";
    };
  };
  elf-info = {
    pname = "elf-info";
    version = "v0.3.0";
    src = fetchFromGitHub {
      owner = "kevin-lesenechal";
      repo = "elf-info";
      rev = "v0.3.0";
      fetchSubmodules = false;
      sha256 = "sha256-wbFVuoarOoxV9FqmuHJ9eZlG4rRqy1rsnuqbGorC2Rk=";
    };
  };
  filetype-nvim = {
    pname = "filetype-nvim";
    version = "15891eb2b138d54b08aef793c43901910ec6879f";
    src = fetchFromGitHub {
      owner = "nathom";
      repo = "filetype.nvim";
      rev = "15891eb2b138d54b08aef793c43901910ec6879f";
      fetchSubmodules = false;
      sha256 = "sha256-Fw7q2k8kGszmzHlSNUYWq4I1IUkmims0JUMMNDGcvSg=";
    };
    date = "2024-05-06";
  };
  geoip-cn = {
    pname = "geoip-cn";
    version = "9628983119056064b70ef946b2d31795503a1252";
    src = fetchurl {
      url = "https://raw.githubusercontent.com/SagerNet/sing-geoip/9628983119056064b70ef946b2d31795503a1252/geoip-cn.srs";
      sha256 = "sha256-lu01BxF+a5BKxYdsNLtd8XEW6zLCxEOwL9HNZZ4KNSc=";
    };
    date = "2025-04-12";
  };
  geosite-cn = {
    pname = "geosite-cn";
    version = "ce7f637d93135bc479767c20c6fbf38f025e5963";
    src = fetchurl {
      url = "https://raw.githubusercontent.com/SagerNet/sing-geosite/ce7f637d93135bc479767c20c6fbf38f025e5963/geosite-cn.srs";
      sha256 = "sha256-oHPy2FBD1iO8GNm5gpAjkp2C5gS2uFvZAAeDdGFGpgc=";
    };
    date = "2025-04-08";
  };
  goauthing = {
    pname = "goauthing";
    version = "v2.3.5";
    src = fetchFromGitHub {
      owner = "z4yx";
      repo = "GoAuthing";
      rev = "v2.3.5";
      fetchSubmodules = false;
      sha256 = "sha256-pZD54SoumOoSOE+r2Llgw71h8wkJ15pqkPX/LRS2R2Y=";
    };
  };
  i3-volume = {
    pname = "i3-volume";
    version = "v3.9.0";
    src = fetchFromGitHub {
      owner = "hastinbe";
      repo = "i3-volume";
      rev = "v3.9.0";
      fetchSubmodules = false;
      sha256 = "sha256-vmyfEXJ/5TRWIJQCblYcy8owI03F+ARNAEd0ni5ublM=";
    };
  };
  libaribcaption = {
    pname = "libaribcaption";
    version = "v1.1.1";
    src = fetchFromGitHub {
      owner = "xqq";
      repo = "libaribcaption";
      rev = "v1.1.1";
      fetchSubmodules = false;
      sha256 = "sha256-x6l0ZrTktSsqfDLVRXpQtUOruhfc8RF3yT991UVZiKA=";
    };
  };
  logchecker = {
    pname = "logchecker";
    version = "0.14.0";
    src = fetchFromGitHub {
      owner = "OPSnet";
      repo = "Logchecker";
      rev = "0.14.0";
      fetchSubmodules = false;
      sha256 = "sha256-LirtDmR1/eVonXjyhbGluRiOPqo+I8tH8rjmFKYhbVM=";
    };
  };
  music-tag = {
    pname = "music-tag";
    version = "0.4.3";
    src = fetchurl {
      url = "https://pypi.org/packages/source/m/music-tag/music-tag-0.4.3.tar.gz";
      sha256 = "sha256-Cqtubu2o3w9TFuwtIZC9dFYbfgNWKrCRzo1Wh828//Y=";
    };
  };
  opentype-feature-freezer = {
    pname = "opentype-feature-freezer";
    version = "1.32.2";
    src = fetchurl {
      url = "https://pypi.org/packages/source/o/opentype-feature-freezer/opentype-feature-freezer-1.32.2.tar.gz";
      sha256 = "sha256-zckzIL/uTi8UVUdvK1YY2C9HwNhlMvG2lnNmatzCtXM=";
    };
  };
  pb = {
    pname = "pb";
    version = "2e26036844a58c38beff00733061bfe55fb176b8";
    src = fetchFromGitHub {
      owner = "SharzyL";
      repo = "pastebin-worker";
      rev = "2e26036844a58c38beff00733061bfe55fb176b8";
      fetchSubmodules = false;
      sha256 = "sha256-LsDssDJZqxtzPi1stAF0jd9u6QrnCvBkCOI3i8oO9a8=";
    };
    date = "2024-12-22";
  };
  pprp = {
    pname = "pprp";
    version = "0.2.7";
    src = fetchurl {
      url = "https://pypi.org/packages/source/p/pprp/pprp-0.2.7.tar.gz";
      sha256 = "sha256-2ednecxSsJONvH9XJ6GV3ExgdcPrUEAlYRpZt2Nrkw0=";
    };
  };
  python-ddns = {
    pname = "python-ddns";
    version = "3.1.5";
    src = fetchurl {
      url = "https://pypi.org/packages/source/d/ddns/ddns-3.1.5.tar.gz";
      sha256 = "sha256-A5waWuTsC/YNLaN3fCzhw1V7MZI+uepSbdW+NR8OA84=";
    };
  };
  rait = {
    pname = "rait";
    version = "278188c8bae13165aa70b6a2fbbb99101fd6f4cd";
    src = fetchgit {
      url = "https://gitlab.com/NickCao/RAIT";
      rev = "278188c8bae13165aa70b6a2fbbb99101fd6f4cd";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-6Y0s5/HUmWrZA6QmV5wYjB1M0Ab/jHM3TSruRpMRwtA=";
    };
    date = "2022-10-07";
  };
  rime-dict = {
    pname = "rime-dict";
    version = "f6583b1c4bf622a81ea77c03ef1d0decf31f01d9";
    src = fetchFromGitHub {
      owner = "xiaoTaoist";
      repo = "rime-dict";
      rev = "f6583b1c4bf622a81ea77c03ef1d0decf31f01d9";
      fetchSubmodules = false;
      sha256 = "sha256-YreRy3HJiO5QEZPe2JAl6o/tq7qQKTqFQ6B2gaurXj8=";
    };
    date = "2018-03-06";
  };
  rime-double-pinyin = {
    pname = "rime-double-pinyin";
    version = "69bf85d4dfe8bac139c36abbd68d530b8b6622ea";
    src = fetchFromGitHub {
      owner = "rime";
      repo = "rime-double-pinyin";
      rev = "69bf85d4dfe8bac139c36abbd68d530b8b6622ea";
      fetchSubmodules = false;
      sha256 = "sha256-UyVzp0TMq7yq5pXQpy7xkPnc1+RF8oVdIXzvrYqLfCQ=";
    };
    date = "2019-01-20";
  };
  rime-essay = {
    pname = "rime-essay";
    version = "573bbeb53e53d4331fff5fae151b814c67b8d0cd";
    src = fetchFromGitHub {
      owner = "rime";
      repo = "rime-essay";
      rev = "573bbeb53e53d4331fff5fae151b814c67b8d0cd";
      fetchSubmodules = false;
      sha256 = "sha256-41wZiPH0cAhl3yTCdyx1zLR3OoSxv+GHQ3xvm14mNxc=";
    };
    date = "2025-04-07";
  };
  rime-ice = {
    pname = "rime-ice";
    version = "51777daedbe4783c3b79f0246d775e4b6d978cbc";
    src = fetchFromGitHub {
      owner = "iDvel";
      repo = "rime-ice";
      rev = "51777daedbe4783c3b79f0246d775e4b6d978cbc";
      fetchSubmodules = false;
      sha256 = "sha256-cFaFgChhpgEiJw+dHl3Hr3T2UQF+Vy6u36JWY+cYBNo=";
    };
    date = "2025-04-06";
  };
  rime-luna-pinyin = {
    pname = "rime-luna-pinyin";
    version = "781ba525b1e2819170a85f98b0047f5b7450868f";
    src = fetchFromGitHub {
      owner = "rime";
      repo = "rime-luna-pinyin";
      rev = "781ba525b1e2819170a85f98b0047f5b7450868f";
      fetchSubmodules = false;
      sha256 = "sha256-8Zho6o3C7CTeMjVBY79M8qVvC+qsWaLCN2uYVqe5UZg=";
    };
    date = "2025-04-12";
  };
  rime-prelude = {
    pname = "rime-prelude";
    version = "23d4ade2371862ecb51df4699dc51f7389b1ae08";
    src = fetchFromGitHub {
      owner = "rime";
      repo = "rime-prelude";
      rev = "23d4ade2371862ecb51df4699dc51f7389b1ae08";
      fetchSubmodules = false;
      sha256 = "sha256-oz+i1Sy33ItPmhoSVaNz/tZQBHD2ZRaqm4Mz4mA1l6k=";
    };
    date = "2025-04-09";
  };
  rssbot = {
    pname = "rssbot";
    version = "v2.0.0-alpha.13";
    src = fetchurl {
      url = "https://github.com/iovxw/rssbot/releases/download/v2.0.0-alpha.13/rssbot-en-x86_64-unknown-linux-musl";
      sha256 = "sha256-xhyEG+or695T7/zmT8yWh1ME7A2oXn1ZLTxGiSwG2NY=";
    };
  };
  s1-helper = {
    pname = "s1-helper";
    version = "d86dbf1058150b59c3cb71f306a9812fab715c91";
    src = fetchFromGitHub {
      owner = "Fungx";
      repo = "Stage1stHelper";
      rev = "d86dbf1058150b59c3cb71f306a9812fab715c91";
      fetchSubmodules = false;
      sha256 = "sha256-EAtv7dY3Gr/lDJvfqfJXeztreErqhG/2+ZzBPKhAQFY=";
    };
    date = "2021-10-15";
  };
  spiceForMinted = {
    pname = "spiceForMinted";
    version = "9626453f7a5955f81ee892a53481704fc55f5b18";
    src = fetchFromGitHub {
      owner = "salatielGarcia";
      repo = "spiceForMinted";
      rev = "9626453f7a5955f81ee892a53481704fc55f5b18";
      fetchSubmodules = false;
      sha256 = "sha256-grgj4IRUY1pEsTjfvzqQHBhpBIMJh/YUC3am6MiujQ4=";
    };
    date = "2020-05-22";
  };
  subconverter = {
    pname = "subconverter";
    version = "v0.9.0";
    src = fetchurl {
      url = "https://github.com/tindy2013/subconverter/releases/download/v0.9.0/subconverter_linux64.tar.gz";
      sha256 = "sha256-iEptEWgmfroHb83VFxIVus+YwXlIq1JuTLvcrV96Ahc=";
    };
  };
  tree-sitter-just = {
    pname = "tree-sitter-just";
    version = "bb0c898a80644de438e6efe5d88d30bf092935cd";
    src = fetchFromGitHub {
      owner = "IndianBoy42";
      repo = "tree-sitter-just";
      rev = "bb0c898a80644de438e6efe5d88d30bf092935cd";
      fetchSubmodules = false;
      sha256 = "sha256-FwEuH/2R745jsuFaVGNeUTv65xW+MPjbcakRNcAWfZU=";
    };
    date = "2025-01-05";
  };
  vim-barbaric = {
    pname = "vim-barbaric";
    version = "bb4bef87417fc3ad92319f556f02d6658b401288";
    src = fetchFromGitHub {
      owner = "rlue";
      repo = "vim-barbaric";
      rev = "bb4bef87417fc3ad92319f556f02d6658b401288";
      fetchSubmodules = false;
      sha256 = "sha256-d1sH4FTxuXxC9/9ZHcX/xOvWkGmW3DN0DSXK+POdi/Q=";
    };
    date = "2021-05-19";
  };
  wemeet = {
    pname = "wemeet";
    version = "3.19.0.401";
    src = fetchurl {
      url = "https://updatecdn.meeting.qq.com/cos/bb4001c715553579a8b3e496233331d4/TencentMeeting_0300000000_3.19.0.401_x86_64_default.publish.deb";
      sha256 = "sha256-VN/rNn2zA21l6BSzLpQ5Bl9XB2hrMFIa0o0cy2vdLx8=";
    };
  };
}
